### ISSUE TITLE
Followed the instructions but the pod is stuck at the Pending state

### ISSUE THREAD

**Issue by gasci** [Pyrrha/calcom-helm#164]
Hi, thank you for maintaining this helm chart.

1. I created a PostgreSQL database and generated a DATABASE_URL
2. I followed the instructions and created a secret in the cluster with the required ENV variables
3. I disabled the ingress to test the chart locally

```
helm upgrade --install --values helm/calcom/values.yaml calcom calcom/calcom --create-namespace -n calcom

# this goes forever
NAME                      READY   STATUS    RESTARTS   AGE
calcom-554f7bf8db-nvjh9   0/1     Pending   0          93s

# this returns nothing
kubectl logs -n calcom calcom-554f7bf8db-rvkbb
```

**Comment by Pyrrha** [comment]
Hello @gasci,

Thanks for using this project.

Can you provide a `kubectl describe pod calcom-xxx`?

**Comment by gasci** [comment]
Here is the error that I am receiving:

```
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  kube-api-access-lnxc5:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age   From               Message
  ----     ------            ----  ----               -------
  Warning  FailedScheduling  92s   default-scheduler  0/1 nodes are available: 1 node(s) had untolerated taint {node.kubernetes.io/disk-pressure: }. preemption: 0/1 nodes are available: 1 Preemption is not helpful for scheduling.
```

**Comment by gasci** [comment]
![Screenshot 2024-12-17 at 23 52 08](https://github.com/user-attachments/assets/dcdfd7b2-d23c-4847-9232-e5419867f4fa)

![Screenshot 2024-12-17 at 23 53 16](https://github.com/user-attachments/assets/93b327e6-d2f4-469f-aac8-25bcd834faea)

![Screenshot 2024-12-17 at 23 53 41](https://github.com/user-attachments/assets/cb18dcc9-330e-467c-8717-2de7fff5e763)

![Screenshot 2024-12-17 at 23 54 10](https://github.com/user-attachments/assets/42c18cd0-e6ba-4bbe-95df-90994dec6ddc)

**Comment by Pyrrha** [comment]
From your logs:
> Events:
>   Type     Reason            Age   From               Message
>   ----     ------            ----  ----               -------
>   Warning  FailedScheduling  92s   default-scheduler  0/1 nodes are available: 1 node(s) had untolerated taint {node.kubernetes.io/disk-pressure: }. preemption: 0/1 nodes are available: 1 Preemption is not helpful for scheduling.
```

It looks like you’ve a single node in your cluster, which has a problem with the disk used. This issue isn’t chart-related, but is directly linked with your infrastructure.

I suggest you to begin with `kubectl describe node` and iterate from there. [This article](https://medium.com/@by_alex/kubernetes-node-disk-pressure-69acffc5fad1) can help you understand the issue and how to address it.

**Comment by gasci** [comment]
This is my local cluster. Do I need a more sophisticated one with much more resources?

From: Tristan Dietz ***@***.***>
Date: Wednesday, 18. December 2024 at 08:17
To: Pyrrha/calcom-helm ***@***.***>
Cc: Göktuğ Aşcı ***@***.***>, Mention ***@***.***>
Subject: Re: [Pyrrha/calcom-helm] Followed the instructions but the pod is stuck at the Pending state (Issue #164)


From your logs:

Events:
Type Reason Age From Message

________________________________

Warning FailedScheduling 92s default-scheduler 0/1 nodes are available: 1 node(s) had untolerated taint {node.kubernetes.io/disk-pressure: }. preemption: 0/1 nodes are available: 1 Preemption is not helpful for scheduling.


It looks like you’ve a single node in your cluster, which has a problem with the disk used. This issue isn’t chart-related, but is directly linked with your infrastructure.

I suggest you to begin with `kubectl describe node` and iterate from there. [This ***@***.***_alex/kubernetes-node-disk-pressure-69acffc5fad1) can help you understand the issue and how to address it.

**Comment by gasci** [comment]
And I haven’t provisined a PV. Is it mandatory?

From: Göktuğ Aşcı ***@***.***>
Date: Wednesday, 18. December 2024 at 14:25
To: Pyrrha/calcom-helm ***@***.***>, Pyrrha/calcom-helm ***@***.***>
Cc: Mention ***@***.***>
Subject: Re: [Pyrrha/calcom-helm] Followed the instructions but the pod is stuck at the Pending state (Issue #164)

This is my local cluster. Do I need a more sophisticated one with much more resources?

From: Tristan Dietz ***@***.***>
Date: Wednesday, 18. December 2024 at 08:17
To: Pyrrha/calcom-helm ***@***.***>
Cc: Göktuğ Aşcı ***@***.***>, Mention ***@***.***>
Subject: Re: [Pyrrha/calcom-helm] Followed the instructions but the pod is stuck at the Pending state (Issue #164)


From your logs:

Events:
Type Reason Age From Message

________________________________

Warning FailedScheduling 92s default-scheduler 0/1 nodes are available: 1 node(s) had untolerated taint {node.kubernetes.io/disk-pressure: }. preemption: 0/1 nodes are available: 1 Preemption is not helpful for scheduling.


It looks like you’ve a single node in your cluster, which has a problem with the disk used. This issue isn’t chart-related, but is directly linked with your infrastructure.

I suggest you to begin with `kubectl describe node` and iterate from there. [This ***@***.***_alex/kubernetes-node-disk-pressure-69acffc5fad1) can help you understand the issue and how to address it.

**Comment by Pyrrha** [comment]
For the calcom chart you’re using, you doesn’t need persistence. For now this feature doesn’t come with the chart.

You may run this chart on your cluster, however your node is currently unhealthy. You can begin your investigation by looking for the why, by describing your node status using `kubectl describe node` as said previously, and inspect the status of your node.

**Comment by gasci** [comment]
You are right. I fixed it but now I am getting an error because I am running an M1 chip.
Failed to pull image "calcom/cal.com:v4.7.8": no matching manifest for linux/arm64/v8 in the manifest list entries

How can I overcome this?

From: Tristan Dietz ***@***.***>
Date: Wednesday, 18. December 2024 at 16:16
To: Pyrrha/calcom-helm ***@***.***>
Cc: Göktuğ Aşcı ***@***.***>, Mention ***@***.***>
Subject: Re: [Pyrrha/calcom-helm] Followed the instructions but the pod is stuck at the Pending state (Issue #164)


For the calcom chart you’re using, you doesn’t need persistence. For now this feature doesn’t come with the chart.

You may run this chart on your cluster, however your node is currently unhealthy. You can begin your investigation by looking for the why, by describing your node status using kubectl describe node as said previously, and inspect the status of your node.

**Comment by Pyrrha** [comment]
As far as I know, the docker image provided by cal.com (used by this chart) only supports amd64 architecture. You can see it on their official [Docker Hub tags](https://hub.docker.com/r/calcom/cal.com/tags) page.

There’s currently an issue open for that on their repository: https://github.com/calcom/docker/issues/358
