### ISSUE TITLE
More obvious breaking changes

### ISSUE THREAD

**Issue by xeruf** [Pyrrha/calcom-helm#168]
`calcom-stack 0.4.3` included a major postgresql upgrade, which unfortunately is still a manual process.
Would be great to reflect that in the versions e.g. by bumping the chart version or having it in a changelog.

I would also like to get rid of the "magic zero", we could just go for 1.0.0 and then move to 2.0 on a breaking change like that.

**Comment by Pyrrha** [comment]
According to semver specification:
> Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

I need more time to provide features in the chart before releasing the 1.0.0 version. When passing in 1.0.0, I’ll definitely indicate those in major updates.
A  changelog per version already exists under [releases page](https://github.com/Pyrrha/calcom-helm/releases). It’s also readable by bots such as Dependabot/Renovate if needed.
