### ISSUE TITLE
Why two separate charts?

### ISSUE THREAD

**Issue by xeruf** [Pyrrha/calcom-helm#25]
Thanks for making this chart!
Are there application  differences between calcom and calcom-stack, or is it just the extra database?
Because all charts I used so far simply had a `postgresql.enabled` field to toggle whether to deploy the postgres subchart, but maybe I am misunderstanding something.

**Comment by Pyrrha** [comment]
Hello, you're welcome!

It's exactly the database in extra.

The reason why this calcom-helm chart has been created apart is that any database can work for the calcom app. The user can choose an external database different from the PostgreSQL one.

Inside the chart values, I encounter more program functionality-related options than external tools. Here, PostgreSQL is a 3rd party, which can be easily replaced by another one if not needed.

I completely understand your point of view, and it was a big question for me during the creation of the charts. However, I chose to do it apart to show explicitly that PostgreSQL is not a dependency for the chart, but a convenience database for this usage (the stack chart is only a convenience chart itself).

When I will get some time I will look for the best of both patterns, but for now, I'll maintain both.

**Comment by xeruf** [comment]
Thanks for the explanation, but I think the common pattern still is to keep it in one.
For example, Vikunja can use SQLite, MySQL and Postgres but nonetheless the chart includes postgres - but it can still be disabled anytime. The same applies to most charts I used so far.

**Comment by xeruf** [comment]
no chance to reconsider this? :c

**Comment by Pyrrha** [comment]
Hello,

Since there's no new proof for any technical advantage, I won't re-open this issue for now.

Be advised that I'm still thinking about it. I want to perform some major changes In the current chart before releasing the v1.0, and this question is still opened until this version.

After, a major change like this will be more difficult to operate, since the chart will be in stable versions.

Feel free to add some pros & cons, articles to elaborate on your perspective.

**Comment by xeruf** [comment]
I think for me the main annoyance is that for every update, I have to consult two `values.yaml` files for changes.
The other argument for me is that all other charts that offer a bundled database do it in one, be it forgejo, zammad, vikunja...
