### ISSUE TITLE
Issues after chart upgrade

### ISSUE THREAD

**Issue by xeruf** [Pyrrha/calcom-helm#81]
After moving from 0.3.5 to 0.3.13 I get a lot of warnings and an error:

![image](https://github.com/user-attachments/assets/2139e826-3479-42de-841e-5a01ab7c16b9)

I dunno where those common.json warnings are coming from, this does not seem related to any of my configuration.
The error seems to be because NEXT_PUBLIC_API_V2_URL has to be set, testing that right now: https://github.com/calcom/cal.com/blob/84a2e55125c3c6b4ebb0c8cc4f2b76490ca67c4f/.env.example#L369
https://cal.com/docs/enterprise-features/api/api-reference#api-versions

**Comment by xeruf** [comment]
nope, setting that variable does not make a difference

**Comment by xeruf** [comment]
That's fun, chart version 0.3.10 works despite showing the same errors:
![image](https://github.com/user-attachments/assets/ec48c797-66d6-4c6c-a897-f398f6a0b5fb)

**Comment by xeruf** [comment]
Actually it works for a moment, then crashes, on either version

**Comment by Pyrrha** [comment]
Hello @xeruf,

Which issue is chart-related?
As far as I see it looks more than you're experiencing troubles to run the app, within the container.

Thus, the rendering of the chart looks working as it should.

I invite you to open an issue presenting your configuration (without visibles tokens) to https://github.com/calcom/docker.
If there's any lack of environment variables, I can add them to help you solve your issue. I plan to check on them in app/docker repos shortly.

**Comment by Pyrrha** [comment]
Closed for inactivity.
